### ISSUE TITLE
Keep getting "illegal memory access" during training

### ISSUE THREAD

**Issue by fuy34** [magicleap/Atlas#13]
Hi Zak, 

Thanks for sharing the code for your amazing work. 

I am trying to run the training model, but keep getting the error saying ``` illegal memory access was encountered```. It sometimes happens at the very beginning, while sometimes happens in the middle of training. The trackback messages are also various. Please refer to the 2 examples below for the error message. 

I am training only on 2 scenes, with 2 GPUs, python3.7, CUDA 10.2, and open3d==0.9. All the other packages are installed based on the README. I suspect it is related to GPU synchronization and probably pytorch-lightening. 

Do you have any insight for this error? 

Thank you in advance. 

=================
Example 1 -- happen at very begining 
```
----------------------------------------------
0 | backbone2d | Sequential     | 27 M  
1 | backbone3d | EncoderDecoder | 2 M   
2 | heads2d    | PixelHeads     | 0     
3 | heads3d    | VoxelHeads     | 4 K   
Validation sanity check: 0it [00:00, ?it/s]transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
Traceback (most recent call last):                                                                                                                                                 
  File "/home/fuy34/Dropbox/Atlas-master/train.py", line 63, in <module>
    trainer.fit(model)

 ... (omit some Traceback message) 

 File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fuy34/Dropbox/Atlas-master/atlas/heads3d.py", line 202, in forward
    if mask_surface.sum()>0:

RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /opt/conda/conda-bld/pytorch_1587428266983/work/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x4e (0x7f7c71b74b5e in /home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x6d0 (0x7f7c7192fe30 in /home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f7c71b626ed in /home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x51ee0a (0x7f7ca279fe0a in /home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x1a350e (0x5563a0bec50e in /home/fuy34/anaconda3/envs/Atlas/bin/python)
frame #5: <unknown function> + 0x10df7c (0x5563a0b56f7c in /home/fuy34/anaconda3/envs/Atlas/bin/python)
frame #6: <unknown function> + 0x10e0d7 (0x5563a0b570d7 in /home/fuy34/anaconda3/envs/Atlas/bin/python)

```
---------------------
Example 2 -- happens at epoch 4, the scene suddenly reduce to 1 for no reason after one 1 epoch, and the Trackback message is different from the previous one 

```
Epoch 0:   0%|                                                                                                                                               | 0/2 [00:00<?, ?it/s]transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
Epoch 1:   0%|                                                                                                                       | 0/1 [00:00<?, ?it/s, loss=2.557, v_num=mseg]transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
Epoch 2:   0%|                                                                                                                       | 0/1 [00:00<?, ?it/s, loss=2.623, v_num=mseg]transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
Epoch 3:   0%|                                                                                                                       | 0/1 [00:00<?, ?it/s, loss=2.464, v_num=mseg]transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
Epoch 4:   0%|                                                                                                                       | 0/1 [00:00<?, ?it/s, loss=2.419, v_num=mseg]transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
transform tensor([[0., 0., 0.]])
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    trainer.fit(model)
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1058, in fit
    results = self.accelerator_backend.spawn_ddp_children(model)
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_backend.py", line 123, in spawn_ddp_children
    results = self.ddp_train(local_rank, mp_queue=None, model=model, is_master=True)
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_backend.py", line 224, in ddp_train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 1076, in optimizer_closure
    model_ref.backward(self, closure_loss, optimizer, opt_idx)
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/pytorch_lightning/core/hooks.py", line 324, in backward
    loss.backward()
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/fuy34/anaconda3/envs/Atlas/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by fuy34** [comment]
It seems an issue related to ```transforms```. I pass a path in ```load_scannet_nyu40_mapping``` function to locate the ```scannetv2-labels.combined.tsv```. After I copy the file to ```data``` folder as the original code does, the error seems disappear.

**Comment by rutvikokate** [comment]
How to specify to use only one GPU, as I have only one for training . The training exits saying - You requested GPUs: [0, 1, 2, 3, 4, 5, 6, 7]
 But your machine only has: [0]
@fuy34
