### ISSUE TITLE
Generating textured meshes.

### ISSUE THREAD

**Issue by codinghaven** [magicleap/Atlas#25]
How difficult would it be to generate a textured mesh with Atlas?

Thanks!

**Comment by zmurez** [comment]
There is a color head implemented which regresses RGB color: https://github.com/magicleap/Atlas/blob/bee3ddbdb0935cf9aa9fc810e829115c6ab74dc5/atlas/heads3d.py#L211
The results are OK, but quite blurry (unfortunately we do not provide a pretrained model for this configuration).
More work on hyperparameter tuning and network architecture could help with this, along with additional losses like a GAN loss. The simple averaging of feature volumes is also a probable culprit for the network having a hard time just copying the color from the input images without blurring.

If you are willing to pass through the image sequence twice, you can first reconstruct the mesh with Atlas and then in a second pass use existing mesh texturing algorithms to backproject the images onto the mesh.

**Comment by efyphil** [comment]
Sorry, can you help. I got this :
Traceback (most recent call last):
  File "inference.py", line 149, in <module>
    main()
  File "inference.py", line 146, in main
    process(info_file, model, args.num_frames, save_path, i, len(info_files))
  File "inference.py", line 91, in process
    tsdf_pred = model.postprocess(outputs)[0]
  File "/root/Atlas/atlas/model.py", line 310, in postprocess
    color = batch[key+'_color'][i]
KeyError: 'vol_04_color'
all dict keys in batch is dict_keys(['vol_16_tsdf', 'vol_08_tsdf', 'vol_04_tsdf', 'vol_16_semseg', 'vol_08_semseg', 'vol_04_semseg'])
I did something wrong?
