### ISSUE TITLE
AssertionError: Requires pyyaml>=5.1 on colab

### ISSUE THREAD

**Issue by Mikor-mkr** [magicleap/Atlas#27]
While I run the colab script I get an AssertionError when I run the inference cell. How can I fix that, please forgive me if the answer is too obvious.

Traceback (most recent call last):
  File "inference.py", line 24, in <module>
    from atlas.model import VoxelNet
  File "/root/Atlas/atlas/model.py", line 29, in <module>
    from atlas.backbone2d import build_backbone2d
  File "/root/Atlas/atlas/backbone2d.py", line 8, in <module>
    from detectron2.layers import Conv2d, get_norm
  File "/usr/local/lib/python3.6/dist-packages/detectron2/__init__.py", line 5, in <module>
    setup_environment()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/utils/env.py", line 98, in setup_environment
    _configure_libraries()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/utils/env.py", line 80, in _configure_libraries
    assert get_version(yaml) >= (5, 1), "Requires pyyaml>=5.1"
AssertionError: Requires pyyaml>=5.1

**Comment by Mikor-mkr** [comment]
I should just install it.. oh god I need to rest.
