### ISSUE TITLE
Error on running inference on the sample dataset

### ISSUE THREAD

**Issue by Namyalg** [magicleap/Atlas#52]
Traceback (most recent call last):
  File "inference.py", line 24, in <module>
    from atlas.model import VoxelNet
  File "/home/csgfws/3dreconDuplicate/Atlas/atlas/model.py", line 29, in <module>
    from atlas.backbone2d import build_backbone2d
  File "/home/csgfws/3dreconDuplicate/Atlas/atlas/backbone2d.py", line 8, in <module>
    from detectron2.layers import Conv2d, get_norm
  File "/home/csgfws/3dreconDuplicate/env/lib/python3.8/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/csgfws/3dreconDuplicate/env/lib/python3.8/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /home/csgfws/3dreconDuplicate/env/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

The environment has been setup as per the instructions in the README, however on running the command  (python inference.py --model results/release/semseg/final.ckpt --scenes METAROOT/sample/sample1/info.json) the above error occurs

**Comment by Zhiozhio** [comment]
Have you solved this problem? I ran it in docker and got the same problem.

**Comment by Namyalg** [comment]
@Zhiozhio , I was finally able to run it on colab, https://colab.research.google.com/drive/1JCSATIGPHL-AE4S-Qa-jQhhoEY5JNly2?usp=sharing 
Not sure about Docker

**Comment by F3lixP4lm** [comment]
Hi, I had the same error. 
According to the documentation (https://detectron2.readthedocs.io/en/latest/tutorials/install.html#common-installation-issues) the version of detectron2 and torch depends on the CUDA version installed on the computer. 
I was able to solve the error by manually adjusting the project dependencies to my CUDA version.
